### ISSUE TITLE
Test the published version of Projectile Motion in LOL harness

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#46] opened 2017-08-29 20:05 UTC
@kathy-phet expressed an interest in putting Projectile Motion in the LOL platform.  It did not receive LOL testing in the last RC process.  But we should test the one on the PhET website in case it checks out.

Assigned to @ariel-phet for scheduling/prioritization/delegation/labeling.

**Comment by ariel-phet** [comment] 2017-08-29 22:19
Marking as high, since this test should be quick

**Comment by brroberts1231** [comment] 2017-09-01 20:44
Tested on OS X 10.10.5, Safari version 9.0.1 (10601.2.7.2).
Found no issues on the sim from the PhET website.

**Comment by BryceAG** [comment] 2017-09-06 18:41
I'm not sure how many systems or browsers should be tested, but I tested it on Windows 10, Chrome Version 60.0.3112.113 (Official Build) (64-bit).
No issues found.

**Comment by lmulhall-phet** [comment] 2017-09-06 20:53
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra 10.12.6

**Browser/Issues:**

Chrome Version 60.0.3112.113

- No issues found.

Firefox 55.0.3

- I'm not sure if this is an issue, but if the "Time/Range/Height" finder is being dragged across the screen after the "Pause in 5 Seconds" button is clicked, it sometimes moves after the "Resume" button is clicked. Same phenomenon occurs for the tape measure, the target, and the cannon. I found this issue while testing the Pendulum Lab in the LoL harness. (This phenomenon occurs in this sim and the Pendulum Lab sim in Firefox and Safari.)

Steps to Reproduce

1. Select an item to drag around.
2. Click the "Pause in 5 Seconds" button.
3. Move your cursor around quickly and erratically while holding the object. I like to try to make figure 8s.
4. The object should move after the "Resume" button is clicked.

Safari 10.1.2

- Same issue as above. Only difference is that I'm also able to get the cannon's platform to move after clicking the "Resume" button.

**Comment by samreid** [comment] 2017-09-07 07:35
@jonathanolson is that expected behavior based on the new implementation of input handler interruptions?  Can you speculate what is happening?

**Comment by lmulhall-phet** [comment] 2017-09-07 16:23
![sep-07-2017 10-22-22](https://user-images.githubusercontent.com/31285590/30173908-7a4dd1e2-93b6-11e7-97cf-8ae5982e793a.gif)

**Comment by kathy-phet** [comment] 2017-09-07 16:40
For submission of this sim to LOL, I am not concerned about this particular behavior as shown in the video. But @jonathanolson can comment on why it is doing this and whether there needs to be a fix in the main code.

**Comment by phet-steele** [comment] 2017-09-08 16:37
QA's work here is done. The sim works well aside from the issue above.

**Comment by samreid** [comment] 2017-09-08 17:07
Reassigned to @kathy-phet since she said she would assign a designer to send the metadata for completed LOL sims.

**Comment by phet-steele** [comment] 2017-09-18 16:47
> Reassigned to @kathy-phet since she said she would assign a designer to send the metadata for completed LOL sims.

This is also mentioned in phetsims/tasks/issues/890. I'm going to close this issue and reopen the linked one and assign to @kathy-phet. The tasks repo feels like a better place than the QA repo for something assigned to KP.

**Closed by phet-steele** 2017-09-18 16:47 UTC
Labels: QA:spot-check
