### ISSUE TITLE
What should the review/testing status labels be?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#312] opened 2019-05-01 19:25 UTC
From Slack on 5/1/19: (related to https://github.com/phetsims/phet-info/issues/75)
>Ariel Paul [1:07 PM]
>Hear ye Hear ye --- a long standing issue just was resolved to remove certain redundant labels. Someone had let this slip for a long time (pointing to big thumbs at myself). But let it be known the `status:fixed-pending-testing` should no longer exist. In particular for @KatieWoe that label has been collapsed into `status:ready-for-review` so that "review" is a general word for designers reviewing, developers reviewing, or QA testing/reviewing

From there discussion began as to whether this was best and how everyone used both tags.  I have observed them used interchangeably or to denote things like whether or not I should close the issue after.  @pixelzoom mentioned using them to denote if the review was testing or a design/code review.

I would suggest either going through with @ariel-phet's change and relying on instructions/assignments in issue for the nuances described above, or changing the labels to be: `status:ready-for-QA` and `status:ready-for-review`  When it is for review it is either not for QA, or if QA looks/test they do not close it.  Basically, it is not done, even if looked at.  If it is ready for QA we test and close if resolved

**Comment by Denz1994** [comment] 2019-05-01 19:37
In my experience, it is typical for the `status:fixed-pending-testing` label to include instructions for testing. The 'status: ready-for-review' label follows a similar use case with instructions for what should be reviewed. I rather have just one label and vote for 'status: ready-for-review'.

If we are removing the `status:fixed-pending-testing` we should update the QA/issue-templates.

> These issues should have the “status:fixed-pending-testing” label.

**Comment by pixelzoom** [comment] 2019-05-01 21:26
Why is it just "review/testing status" that we're considering?  Like "priority", perhaps issues should only be in one "state" at a time.   Perhaps we should start by describing the lifecycle of GitHub issues in the PhET process as a state machine, then create `state:` labels (or `status:`, if you prefer) that reflects that process.

**Comment by pixelzoom** [comment] 2019-05-01 21:29
I disagree with https://github.com/phetsims/QA/issues/312#issuecomment-488390590.  "Review" is very different than "test".   For example, I currently have Gas Properties issues where the work is done and is "ready-for-review".  Since it's an unpublished sim, those issues will be closed after review is accepted.   For a sim that is published, an issue will typically need to be review by a designer, and that is indicated by "ready-for-review".  When that's completed, I then need to remember to have it tested during an RC cycle, and (according to the QA issue template) I move the issue to the "status:fixed-pending-testing".   If we collapse so states into one, I have no way to determine which have been reviewed, and which are ready for RC testing.

**Comment by KatieWoe** [comment] 2019-05-01 21:36
I would disagree on having multiple tags for different people reviewing, and especially for only having one up at a time.  Quite often a change will be given to both the designer and myself to look over at the same time.  It seems silly to delay one of us looking in this case.  An issue may be in a set "state" of review, but that doesn't mean that only one type of review is relevant and happening at that time.

**Comment by pixelzoom** [comment] 2019-05-01 21:43
> I would disagree on having multiple tags for different people reviewing, and especially for only having one up at a time. Quite often a change will be given to both the designer and myself to look over at the same time. 

There's nothing preventing you and a designer from both reviewing an issue that is in the "ready-to-review" state.   And until a designer has reviewed the work, you certainly shouldn't be doing a full regression test on an issue.  `status: ready-for-review` means that work is ready to be reviewed, not thoroughly tested.  `status:fixed-pending-testing` indicates that something is ready for a full regression test, and comes after a review.  They are 2 different activities.

**Comment by zepumph** [comment] 2019-05-01 22:13
@pixelzoom I like the point of looking into the lifecycle of a github issue and creating labels that actually make sense for the tasks needed. I wonder though if the stage in the lifecycle is clear enough via assigning. If there is a single review label, and a designer is assigned, that feels obviously different to me than if QA is assigned to it with the same label. Do you feel like there would ever be overlap such that this could be confusing? In general I feel that may be more complexity than needed for a single github issue.

**Comment by pixelzoom** [comment] 2019-05-01 23:09
Issues (especially those that need to be verified in QA) often remain unassigned for long periods of time.  If you have multiple unassigned issues for my sim labeled with one "review" label, how do you know (without inspecting each issue) which issues need to be vetted by a designer, and which ones need to be vetted during RC testing?     This is not a hypothetical case.  I use these 2 labels all the time.  And I'm happy to replace them with something else, but not something that makes managing issues more difficult.

**Comment by pixelzoom** [comment] 2019-05-01 23:09
Relying on who is assigned to determine what state an issue is in is (for me) a non-solution. 

Issues (especially those that need to be verified in QA) often remain unassigned for long periods of time.  If you have multiple unassigned issues for my sim labeled with one "review" label, how do you know (without inspecting each issue) which issues need to be vetted by a designer, and which ones need to be vetted during RC testing?     This is not a hypothetical case.  I use these 2 labels all the time.  And I'm happy to replace them with something else, but not something that makes managing issues more difficult.

**Comment by samreid** [comment] 2019-05-02 18:41
We discussed changing "status:fixed:pending-testing" to "status:ready-for-qa".
"fixed-pending-deploy" and "???" could be collapsed.
The website can use a repo-specific "fixed-pending-deploy" label.

@jbphet and @Denz1994 use "fixed-pending-deploy" to know when to notify clients.

@KatieWoe needs a way to know whether to close issues after testing them.

"ready-for-review" will mean reassign to author when done.  
"ready-for-qa" will mean close if it passes QA test.

Main label lifecycle for an issue in a sim pre RC branches:
unlabeled -> ready-for-review -> ready-for-qa -> closed

Main label lifecycle for an issue in a sim with RC branches:
unlabeled -> ready-for-review -> ready-for-qa  -> fixed-awaiting-deploy -> closed

Can also mention "feel free to close if all is well".  But default would be to assign back.

if a dev test, "ready-for-qa" should be closed
if an rc test, "ready-for-qa" should be moved to fixed-awaiting-deploy

What about issues that do not require QA?
For sims that have release branches, we should be more careful about this lifecycle.  For initial 1.0 sims, we do not need all this tracking.

@zepumph points out the advantage of seeing green/red open/closed linked from RC issues.

**Comment by samreid** [comment] 2019-05-02 18:53
Summary:

The main philosophy for "ready-for-qa" labeled issues: close issues if they don't require further issue-specific work. (Deploying the sim doesn't count as issue-specific work).

The default for "ready-for-review" is to reassign to author.

Keep fixed-pending-deploy for edge cases, like clients that need to be emailed.  That is the exception rather than the rule.

Action items:
@KatieWoe will update the template.
@mattpen will make "status:ready-for-qa" label.

**Comment by KatieWoe** [comment] 2019-05-02 19:18
QA book and issue template updated.

**Comment by mattpen** [comment] 2019-05-06 14:58
New label has been added to all repos.

**Closed by mattpen** 2019-05-06 14:58 UTC
