### ISSUE TITLE
Evaluate Safari bug for in PhET's published simulations

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/qa#854] opened 2022-11-14 16:45 UTC
Please do a quick check of published simulations at phet.colorado.edu, and look for the Safari bug (in Safari 16). This bug was seen in Geometric Optics (https://github.com/phetsims/scenery/issues/1503), Mean Share and Balance (https://github.com/phetsims/mean-share-and-balance/issues/122) and Gravity and Orbits (https://github.com/phetsims/gravity-and-orbits/issues/435). 

Please test and answer the following questions: 
- Is there an artifact seen in the published sim? 
- Is there an artifact seen now on master? (e.g. did JO's fixes fix it on master). 

@jonathanolson - Which sims are most likely to exhibit artifacts? 

- [ ] Acid-Base Solutions
- [ ] Area Builder
- [ ] Area Model Algebra
- [ ] Area Model Decimals
- [ ] Area Model Introduction
- [ ] Area Model Multiplication
- [ ] Arithmetic
- [ ] Atomic Interactions
- [ ] Balancing Act
- [ ] Balancing Chemical Equations
- [ ] Balloons and Static Electricity
- [ ] Beer's Law Lab
- [ ] Bending Light
- [ ] Blackbody Spectrum
- [ ] Build a Fraction
- [ ] Build a Molecule
- [ ] Build a Nucleus
- [ ] Build an Atom
- [ ] Capacitor Lab: Basics
- [ ] Center and Variability
- [ ] Charges and Fields
- [ ] Circuit Construction Kit: AC
- [ ] Circuit Construction Kit: AC - Virtual Lab
- [ ] Circuit Construction Kit: DC
- [ ] Circuit Construction Kit: DC - Virtual Lab
- [ ] Collision Lab
- [ ] Color Vision
- [ ] Concentration
- [ ] Coulomb's Law
- [ ] Curve Fitting
- [ ] Density
- [ ] Diffusion
- [ ] Energy Forms and Changes
- [ ] Energy Skate Park
- [ ] Energy Skate Park: Basics
- [ ] Equality Explorer
- [ ] Equality Explorer: Basics
- [ ] Equality Explorer: Two Variables
- [ ] Expression Exchange
- [ ] Faraday's Law
- [ ] Forces and Motion: Basics
- [ ] Fourier: Making Waves
- [ ] Fraction Matcher
- [ ] Fractions: Equality
- [ ] Fractions: Intro
- [ ] Fractions: Mixed Numbers
- [ ] Friction
- [ ] Function Builder
- [ ] Function Builder: Basics
- [ ] Gas Properties
- [ ] Gases Intro
- [ ] Gene Expression Essentials
- [ ] Geometric Optics
- [ ] Graphing Lines
- [ ] Graphing Quadratics
- [ ] Graphing Slope-Intercept
- [ ] Gravity and Orbits
- [ ] Gravity Force Lab
- [ ] Gravity Force Lab: Basics
- [ ] Greenhouse Effect
- [ ] Hooke's Law
- [ ] Isotopes and Atomic Mass
- [ ] John Travoltage
- [ ] Least-Squares Regression
- [ ] Make a Ten
- [ ] Masses and Springs
- [ ] Masses and Springs: Basics
- [ ] Molarity
- [ ] Molecule Polarity
- [ ] Molecule Shapes
- [ ] Molecule Shapes: Basics
- [ ] Molecules and Light
- [ ] Natural Selection
- [ ] Neuron
- [ ] Normal Modes
- [ ] Number Line: Distance
- [ ] Number Line: Integers
- [ ] Number Line: Operations
- [ ] Number Play
- [x] Ohm's Law
- [x] Pendulum Lab
- [x] pH Scale
- [ ] pH Scale: Basics
- [x] Plinko Probability
- [x] Projectile Motion
- [x] Proportion Playground
- [x] Ratio and Proportion
- [x] Reactants, Products and Leftovers
- [x] Resistance in a Wire
- [x] Rutherford Scattering
- [x] States of Matter
- [x] States of Matter: Basics
- [x] Trig Tour
- [x] Under Pressure
- [x] Unit Rates
- [x] Vector Addition
- [x] Vector Addition: Equations
- [x] Wave Interference
- [x] Wave on a String
- [x] Waves Intro

**Comment by Nancy-Salpepi** [comment] 2022-11-14 18:25
in published waves intro, I see an artifact in the graph on the Water screen that is fixed in master.
<img width="605" alt="Screenshot 2022-11-14 at 1 22 04 PM" src="https://user-images.githubusercontent.com/87318828/201737303-753e4bae-a0d7-4e33-8425-55e7a9443585.png">

**Comment by Nancy-Salpepi** [comment] 2022-11-14 19:19
Artifacts in trig tour still seen on master:
<img width="527" alt="Screenshot 2022-11-14 at 2 15 33 PM" src="https://user-images.githubusercontent.com/87318828/201746330-fcf40ae7-9c68-4b96-992b-9a5acfc28e62.png">

Steps: slowly move red point on the circle--completing more than one 360 degree rotation.

**Comment by jonathanolson** [comment] 2022-11-14 19:26
I'm able to reproduce the trig tour bug, and I should be able to narrow it down quickly (it seems to be present when I take a snapshot of the SVG)

**Comment by Nancy-Salpepi** [comment] 2022-11-14 19:29
I also see one with States of Matter that is still present on master:
<img width="527" alt="Screenshot 2022-11-14 at 2 28 23 PM" src="https://user-images.githubusercontent.com/87318828/201748527-051146c2-9f4b-457d-baa4-d138b923d112.png">

**Comment by Nancy-Salpepi** [comment] 2022-11-14 19:38
Resistance in a Wire also showing artifacts on master
<img width="527" alt="Screenshot 2022-11-14 at 2 37 05 PM" src="https://user-images.githubusercontent.com/87318828/201750154-c24fc065-3e49-4dc0-9bb8-f92f3fca83f6.png">

To reproduce--adjust the Area.

**Comment by jonathanolson** [comment] 2022-11-14 19:51
Trig tour case is buggy with no workaround known yet. The clip area is showing the same issue, so it's leaking through some of the background (in this case, I'm showing the background at 0.1 opacity):

<img width="187" alt="image" src="https://user-images.githubusercontent.com/480878/201752285-c6140e2c-85e4-41d7-b835-2dc3dab56751.png">

Minimum reproducible example below (with the spiral image redacted, since it puts over character limits):
<details>

```html
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Bug example</title>
</head>

<body style="background-color: white;">
  <svg width="1012" height="816">
    <defs>
      <clipPath id="clip113" clipPathUnits="userSpaceOnUse">
        <path
            d="M -13.41536647912858271070 -48.37424875107316069034 A 51.77079632679519249905 51.77079632679519249905 0 1 0 14.25492059817330492422 51.40158310364876825815 L 14.25492059817330314786 51.40158310364876115273 A 54.91238898038498206233 54.91238898038498206233 0 1 0 -15.09447471721803069045 -54.42891745622437582597 L -13.41536647912858271070 -48.37424875107316069034 Z M0 0"></path>
      </clipPath>
    </defs>
    <g transform="matrix(0.98828125000000000000,0,0,0.98828125000000000000,0,76.26692708333331438553)">
      <g transform="translate(513,215.35000000000002273737)">
        <g clip-path="url(#clip113)">
          <g transform="matrix(0.33333333333333331483,0,0,0.33333333333333331483,-194.09999999999999431566,-192.40000000000000568434)">
            <rect x="0" y="0" width="1155px" height="1164px" style="fill: #f00;"></rect>
            <image x="0" y="0" width="1155px" height="1164px"
                   xlink:href="..."></image>
          </g>
        </g>
      </g>
    </g>
  </svg>
</body>
</html>
```

</details>

**Comment by jonathanolson** [comment] 2022-11-14 20:07
<img width="170" alt="image" src="https://user-images.githubusercontent.com/480878/201755307-2b865ad9-7aa8-4438-b8f1-ffd888723e88.png">

It's showing up... with `?rootRenderer=canvas`, with things confirmed as rendering in Canvas.

**Comment by Nancy-Salpepi** [comment] 2022-11-14 20:18
Artifacts in Projectile Motion on the Vectors screen look fixed on master.
<img width="278" alt="Screenshot 2022-11-14 at 3 14 49 PM" src="https://user-images.githubusercontent.com/87318828/201756987-40d15178-31d4-4bd0-b11d-9e0e75994d0e.png">

**Comment by Nancy-Salpepi** [comment] 2022-11-14 20:45
Artifacts on the Lab screen of Pendulum Lab and in Ohm's Law also look fixed on master
<img width="227" alt="Screenshot 2022-11-14 at 3 30 33 PM" src="https://user-images.githubusercontent.com/87318828/201760512-9aa05ff6-1170-42b8-949d-05c076ee0087.png">

<img width="396" alt="Screenshot 2022-11-14 at 3 42 19 PM" src="https://user-images.githubusercontent.com/87318828/201762010-696248bb-bde8-47ac-95e3-0708d3e96846.png">

**Comment by jonathanolson** [comment] 2022-11-14 21:54
<img width="493" alt="image" src="https://user-images.githubusercontent.com/480878/201775898-83f716f9-9596-4562-bf90-b05516a0fece.png">

Buggy case in Safari's technology preview too.

```html
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Bug example</title>
</head>

<body style="background-color: white;">
  <svg width="1012" height="816">
    <defs>
      <clipPath id="clip" clipPathUnits="userSpaceOnUse">
        <path
            d="M -13.41536647912858271070 -48.37424875107316069034 A 51.77079632679519249905 51.77079632679519249905 0 1 0 14.25492059817330492422 51.40158310364876825815 A 54.91238898038498206233 54.91238898038498206233 0 1 0 -15.09447471721803069045 -54.42891745622437582597 Z"></path>
      </clipPath>
    </defs>
    <g transform="matrix(0.98828125000000000000,0,0,0.98828125000000000000,100,100)" clip-path="url(#clip)">
      <image x="-500px" y="-500px" width="1155px" height="1164px"
             xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAABNJREFUCB1jZGBg+A/EDEwgAgQADigBA//q6GsAAAAASUVORK5CYII%3D"></image>
    </g>
  </svg>
</body>
</html>
```

**Comment by jonathanolson** [comment] 2022-11-14 21:58
Some of the bugs look related to https://bugs.webkit.org/show_bug.cgi?id=114579.

**Comment by kathy-phet** [comment] 2022-11-14 22:07
@jonathanolson - What is your recommendation here? Is this something we should work around? Or is this a bug we report and on Safari to fix? Or both?

**Comment by kathy-phet** [comment] 2022-11-14 22:51
@Nancy-Salpepi - Please test on iPads/iPhones. Thanks!

**Comment by Nancy-Salpepi** [comment] 2022-11-14 23:15
The artifacts seen on master with the mac for Trig Tour, States of Matter and Resistance in a Wire are also seen on the iPad 9th generation with iPadOS 16. In order to see them on the iPad, you need to be zoomed in first. 

@jonathanolson did you also want me to look at the sims that are fixed on master but show artifacts in published?

**Comment by Nancy-Salpepi** [comment] 2022-11-14 23:53
I will go back and take a look at the sims with issues tomorrow using mac/iPad + chrome.

**Comment by Nancy-Salpepi** [comment] 2022-11-15 13:57
I do see the same artifacts I reported earlier using iPadOS 16 and Chrome as well--Trig Tour, States of Matter, and Resistance in a Wire have artifacts on master. I don't see artifacts on States of Matter published because I can't zoom in. 
I see the artifacts for Waves intro and Projectile motion on published but not on master. 

I don't see any issues with mac + chrome.

**Comment by kathy-phet** [comment] 2022-11-29 19:59
Testing on this is sufficient. We've done what we will do for now. Closing this test issue.

**Closed** 2022-11-29 19:59 UTC
Labels: priority:2-high
