### ISSUE TITLE
Firefox slight lag on sliders

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#346] opened 2019-06-14 22:51 UTC
For https://github.com/phetsims/QA/issues/345. In published version to less noticeable degree.  Even here the issue is very slight.
On Win 10 Firefox

There's a tiny bit of lag in firefox when the first slider is at the top and you are dragging the second to the bottom.  Very small amount.
![bitoflagbelow](https://user-images.githubusercontent.com/41024075/59542731-9f5e4380-8ec4-11e9-8339-3ea3a8c83ed7.gif)

**Comment by jessegreenberg** [comment] 2019-06-14 23:02
Thanks @KatieWoe, it is quite fast on my desktop I am going to try a slower machine.

**Comment by jessegreenberg** [comment] 2019-06-14 23:35
The problem is still there when a11y and sound are both disabled, so the issue must be graphical, likely relating to the large text or arrows. I am not able to get much information from the Firefox performance tool.

**Comment by jessegreenberg** [comment] 2019-06-15 00:18
This is also an issue for the voltage slider when the resistance is very low, indicating again this is related to large current rather than the resistance slider specifically.

I tried a few things related to reducing bounds in case there was an easy fix (preventFit formula and arrows, boundsMethod: fast on formula letters). I don't see much of a difference, but the issue is pretty minor anyway. The slow down is mostly in the range form 10 - 50 ohms.

@ariel-phet can you review, and does this require more time/block publication?

**Comment by ariel-phet** [comment] 2019-06-17 18:58
@jessegreenberg I see this as a non-issue personally. I cannot even see a lag on my old windows desktop. And what is shown in the video comment above is not alarming to me at all. Marking as `wontfix` but assigning back to you to close.

**Comment by jessegreenberg** [comment] 2019-06-17 19:13
Thanks @ariel-phet, closing.

**Closed by jessegreenberg** 2019-06-17 19:13 UTC
Labels: type:performance
