### ISSUE TITLE
Dev test: Android App 2.0.4(45)

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#612] opened 2021-02-19 18:23 UTC
Version 2.0.4 (Build 44) has been released as an internal test track for the Android app.

It is available here: https://play.google.com/apps/internaltest/4697762600441754675

This fix addresses the bug described in phetsims/phet-android-app#154.  Part of this fix involves verifying that you can recreate the bug in the current version from the play store. Then, without taking additional action, verifying that updating to the internal test track version fixes that bug.

Here's how I've been recreating that bug:
1. Install the production version of the app.  Make sure it is on 2.0.2 (42) or earlier.
2. Go to App Info > Storage > Delete Data (not just the cache).  This step will be different depending on the current android version, but usually long tapping on the app icon in the app launcher will get you there.
3. Launch the app, return immediately to App Info, and hit Force Quit.  This step needs to be done as quickly as possible.
4. Launch the app, then either observe a crash or scroll to the bottom of the collection and observe a crash.
5. These steps might not work every time, you might need to go back to step 2. several times before the timing works out.

After this bug triggers, it will be persistent unless you delete the data again without an immediate force quit. Once the bug is persisting, try upgrading to the latest dev version and launching the app.  You should be able to scroll without a crash, although some sims may be missing.  The missing sims should show up after using the app for a while (10 seconds or so).

It's not clear to me how to easily switch from the production version to the internal test version.  @KatieWoe - let me know if you need help figuring this out.

**Comment by mattpen** [comment] 2021-02-19 20:30
@KatieWoe - There is one more change coming for this test, which will published early next week, so please hold off this test for now.

**Comment by KatieWoe** [comment] 2021-02-19 20:42
Ok. I was trying to make progress and I think I made things even stranger on my end, so when it is ready, let me know because I may need help again. Sorry

**Comment by mattpen** [comment] 2021-02-23 19:57
@KatieWoe - this is ready for testing again, but it will now be build 45 instead of 44.  We should still test the upgrade from 2.0.2 to 2.0.4.

**Comment by KatieWoe** [comment] 2021-02-25 22:28
Reproduced bug on published app on both tablet (Android 8.1) and ChromeOS. Updating to dev version of app does seem to have stopped the crashing behavior in both cases. Will now test both more in-depth to look for regressions.

**Comment by KatieWoe** [comment] 2021-02-26 22:58
I did see one instance of crashing behavior on the tablet with Android 8.1. I had just switched languages, entered a sim, and left it. Upon leaving the app closed itself. The crashing behavior did not seem to persist.

**Comment by KatieWoe** [comment] 2021-02-26 22:59
QA is done. Found a few worrying behaviors that I was unable to reproduce reliably.

**Comment by mattpen** [comment] 2021-03-06 05:21
The changes for this test were published last night. closing.

**Closed** 2021-03-06 05:22 UTC
