### ISSUE TITLE
RC test: Coulomb's Law 1.0.0-rc.1

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#210] opened 2018-10-16 18:13 UTC
@KatieWoe, @arouinfar, @jessegreenberg,  coulombs-law/1.0.0-rc.1 is ready for RC testing. Document issues in https://github.com/phetsims/coulombs-law/issues and link to this issue. This is the first RC testing the sim has received. Additionally, it's the first RC testing using Inverse Square Law Common.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>
We added the ability to activate a 'projector' that's useful for certain presentation contexts and for printing the sim. It has the black background removed and some borders added. Can you make a note to run through some testing with `colorProfile=projector` as a query parameter as well to ensure the visual changes don't affect the sim in some unforeseen way? 

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.1/phet/coulombs-law_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.1/phet/coulombs-law_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.1/phet/xhtml/coulombs-law_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/17BEdTv1KM1Tq6kyi3fxo15znqRH6iw8pyc4axE47eeM/edit#gid=581789047)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - ~~Test all forms of input with a screen reader (if applicable).~~

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.1/phet/coulombs-law_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.1/phet/coulombs-law_en_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/17BEdTv1KM1Tq6kyi3fxo15znqRH6iw8pyc4axE47eeM/edit#gid=581789047)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a screen reader.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by emily-phet** [comment] 2018-10-17 12:44
@mbarlow12 Just checked out this version and noticed something. Not sure if this has been noticed/discussed before. When focus is on the charge value slider, pressing shift+arrow results in the a left or right tweaker button looking depressed, but nothing happens. Shouldn't this move the slider?

**Comment by jessegreenberg** [comment] 2018-10-17 13:30
That looks like a regression that was introduced for all things using AccessibleNumberSpinner, I see the same problem in rutherford-scattering.

**Comment by KatieWoe** [comment] 2018-10-17 15:17
Good catch @emily-phet

**Comment by KatieWoe** [comment] 2018-10-18 18:38
QA is Done.  Double Checking that there is no screen reader support.  @mbarlow12

**Comment by mbarlow12** [comment] 2018-10-18 18:43
@KatieWoe that's correct. We decided to add greater a11y support in 1.1+ releases.

**Comment by lmulhall-phet** [comment] 2018-10-18 18:59
> We decided to add greater a11y support in 1.1+ releases.

Is this going the general procedure for all sims?

**Comment by emily-phet** [comment] 2018-10-18 19:37
@lmulhall-phet - nothing general. A11y inclusion will still be decided on a sim-by-sim basis.

**Comment by mbarlow12** [comment] 2018-10-24 18:32
Latest updates to 1.0 branch at https://github.com/phetsims/coulombs-law/commit/9ca81f70a8f938f4d48cbd73b4893127efc86d6e.

**Comment by mbarlow12** [comment] 2018-10-30 20:39
New rc at:
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-rc.4/phet/coulombs-law_en_phet.html

@KatieWoe should I make a new RC test issue?

**Comment by KatieWoe** [comment] 2018-10-30 20:48
@mbarlow12 Yes please, including any tests you want done and issues you want checked.  Let me know if you need any help.  And please close this issue when the new one goes up unless you need it open.

**Comment by mbarlow12** [comment] 2018-11-01 16:03
New RC test issue at https://github.com/phetsims/QA/issues/214

**Closed** 2018-11-01 16:03 UTC
Labels: QA:rc-test
